import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const headerPath = path.join(root, "userscript", "metadata.txt");
const srcDir = path.join(root, "userscript", "src");
const outPath = path.join(root, "dist", "tweet-discord-share.user.js");

const header = fs.readFileSync(headerPath, "utf8").trimEnd();
const modules = fs
  .readdirSync(srcDir)
  .filter((name) => name.endsWith(".js"))
  .sort();

if (modules.length === 0) {
  console.error("No source modules found in userscript/src/");
  process.exit(1);
}

const body = modules
  .map((name) => {
    const filePath = path.join(srcDir, name);
    return `  // --- ${name} ---\n${fs.readFileSync(filePath, "utf8").trimEnd()}`;
  })
  .join("\n\n");

const generated = [
  header,
  "",
  "// Generated by `npm run build`. Edit userscript/src/ instead of this file.",
  "",
  "(function () {",
  '  "use strict";',
  "",
  body,
  "})();",
  ""
].join("\n");

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, generated, "utf8");

console.log(`Built ${outPath} (${modules.length} modules)`);
